### ISSUE TITLE
Tracking issues of reviving Ceph Rust

### ISSUE THREAD

**Issue by Xuanwo** [ceph/ceph-rust#91]
Hello, everyone. I'm Xuanwo. I just received write permission for this project and plan to revive it. I'm not an expert in Ceph and have never contributed to it before, so I truly need the support of the entire community!

The ceph-rust project has been inactive for two years. We need to perform some cleanup to ensure the project is in good condition before releasing anything. This issue is being used to track the tasks involved in reviving ceph-rust.

## Tasks

- [ ] Review pull requests and close them if they are no longer valid.
- [x] Check and update github actions to make sure they still work.
  - [x] https://github.com/ceph/ceph-rust/issues/92
- [x] #97
- [x] #101
- [ ] Upgrade our dependences.

**Comment by spdfnet** [comment]
I've done the last two on my own before, nothing big, they take 1 hour at most.

The most important other things are adding support for current Ceph versions (only boilerplate) and update dependencies.

And the thing that is never done properly anywhere, have proper documentation.
Mentioning how this library interacts with the ceph-mon, uses the `libc` crate, librados dynamic C library and how it all works  together (and how it doesn't) with Linux is key.

As an extra, this crate was designed with a specific purpose in mind, is not generic and has a couple of pitfalls.
There is a lot of unnecessary code that should be removed IMO.

**Comment by Xuanwo** [comment]
> I've done the last two on my own before, nothing big, they take 1 hour at most.

Would you like to submit PRs for this?

> The most important other things are adding support for current Ceph versions (only boilerplate) and update dependencies.

Agreed.

> Mentioning how this library interacts with the ceph-mon, uses the libc crate, librados dynamic C library and how it all works together (and how it doesn't) with Linux is key.

Here is my :100: support.

> As an extra, this crate was designed with a specific purpose in mind, is not generic and has a couple of pitfalls.
There is a lot of unnecessary code that should be removed IMO.

Would you like to start a new issue with details?
